name: pilot
channels:
  - conda-forge
dependencies:
  - python=3.10.19
  - pip
  - pip:
      - --index-url https://download.pytorch.org/whl/cu121
      - torch==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - torchaudio==2.5.1+cu121
      - --extra-index-url https://pypi.org/simple

      - transformers==5.1.0
      - datasets==4.5.0
      - peft==0.12.0
      - tqdm==4.67.1
      - accelerate==1.12.0
      - huggingface-hub==1.4.1
      - safetensors==0.4.5

      - sentencepiece
      - packaging
      - numpy
      - pyyaml